public with sharing class AccountTriggerHandler {
/*List<Contact> ContactList1 = new List<Contact>();
List<Contact> ContactList2 = new List<Contact>();

public void AfterInsert(List<Account> newAcc) {
    for(Account acc: newAcc){
        ContactList1.add(new Contact(LastName='TestCon', AccountId = acc.Id));
    }
    insert ContactList1();
}
public void AfterUpdate(List<Account> newAcc) {
List<Contact> conList= [Select Id ,LastName, AccountId from contact where AccountId IN: newAcc];
if(conList.size() == 0){
for(Account acc: newAcc){
    ContactList2.add(new Contact(LastName='TestCon', AccountId = acc.Id));

}
insert ContactList2();
}
}*/
}
