public with sharing class arithmaticOperationsNew {
 
    public integer i=20;
    public integer j=10;
   
 public integer add(){
   integer total i + j;
   return total;
   }
 public integer sub(){
    integer total i - j;
    return total;
  }
  public integer sub(){
    integer total i - j;
    return total;
  }
  public integer mul(){
    integer total i * j;
    return total;
  }
  public integer div(){
    integer total i / j;
    return total;
  }
 }
